# Generated by Django 2.1 on 2019-02-12 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('WELCOME', 'WELCOME'), ('OFFER', 'OFFER'), ('SURVEY', 'SURVEY'), ('REQUEST', 'REQUEST'), ('NEWSLETTER', 'NEWSLETTER'), ('ANOUNCEMENT', 'ANOUNCEMENT')], default='WELCOME', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='emailsunsubscribed',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.CustomerView'),
        ),
        migrations.AddField(
            model_name='customerview',
            name='campaign_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.Category'),
        ),
        migrations.AddField(
            model_name='emailsunsubscribed',
            name='campaign_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.Category'),
        ),
    ]
