# Generated by Django 2.1 on 2019-02-13 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20190212_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsunsubscribed',
            name='campaign_category',
        ),
    ]
