# Generated by Django 2.1 on 2019-02-13 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_remove_emailsunsubscribed_campaign_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsinfo',
            name='email_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notify.EmailActivity'),
        ),
    ]
